name: PRODUCTION - Upload Secrets to S3

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::...
        aws-region: me-south-1 

    - name: Create .env file
      run: printf "%s" "${{ secrets.PROD_SECRETS }}" > .env
      
    - name: Upload to S3
      run: aws s3 cp .env s3://...
